baseURL = 'https://www.bsteve.com'
languageCode = 'en-us'
title = "Steve's website"
theme = ["osm", "archie"]
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
	mode = "toggle"
	subtitle = "back in the north and carrying on"
	useCDN = "false"
	mathjax = "false"
	katex = "false"
	enableEmoji = "false"

	

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/stevb"
[[params.social]]
name = "email"
icon = "mail"
url = "mailto:sgb@protonmail.com"

[[menu.main]]
	name = "Main Page"
	url = "/"
	weight = 1
[[menu.main]]
	name = "About Me"
	url = "/about/"
	weight = 2
#[[menu.main]]
#	name = "All posts"
#	url = "/posts"
#	weight = 3
